### ISSUE TITLE
Transient error in 'mri_deface' results in full crashout

### ISSUE THREAD

**Issue by akimbler** [fiuneuro/cis-bidsify#24]
This might have been resolved with the move from `bidsconvert.sh` to full python, but a transient error in `mri_deface` appears to result in the workflow ending prematurely on v0.0.2. 

![image](https://user-images.githubusercontent.com/21314171/79129031-7cb1eb00-7d72-11ea-87c6-13f510e2a0ff.png)

**Comment by tsalo** [comment]
Can we edit `run` so that it prints out the actual error message?
