### ISSUE TITLE
Phasediff jsons need EchoTime1 and EchoTime2 fields

### ISSUE THREAD

**Issue by tsalo** [fiuneuro/cis-bidsify#5]
Currently, it looks like we get one echo time (the later one) as `EchoTime`. We need distinct fields called `EchoTime1` and `EchoTime2`. We should make sure that these aren't fields that exist after conversion, but are being pruned by our code.

**Comment by tsalo** [comment]
@adamkimbler Can you add EchoTime1 and EchoTime2 to your list of KEEP_KEYS in clean_jsons in #7?

**Comment by akimbler** [comment]
@tsalo I addressed this behavior in my most recent commit, I agreed with some of your previous comments, so now clean_metadata cleans out the nested 'global' key, but doesn't remove fields

**Comment by akimbler** [comment]
@tsalo Can this Issue be closed now? I think this was resolved in the most recent release

**Comment by tsalo** [comment]
Sounds good.
