### ISSUE TITLE
Defacing seems to not be working

### ISSUE THREAD

**Issue by tsalo** [fiuneuro/cis-bidsify#57]
It could be an issue with the git-annex symlinking. `mri_deface` seemed like it was working based on the out file, but the actual image was not defaced at all. Then when I tried it manually with `singularity shell`, the file couldn't be loaded.

**Comment by tsalo** [comment]
@mriedel56 Have you had trouble operating on symlinked nifti files after using datalad?

**Comment by akimbler** [comment]
@tsalo is it possible that this is due to permissions on the symlinked niftis? I've been doing some testing and with the wrong permissions `mri_deface` just completes without error without changing the target file

**Comment by tsalo** [comment]
I think it could be.
