### ISSUE TITLE
Multi-echo phase and sbref files have wrong metadata

### ISSUE THREAD

**Issue by tsalo** [fiuneuro/cis-bidsify#8]
At some point our metadata-updating procedure is overwriting the json files for multi-echo SBRef and phase data with the first echo's metadata. It could be a problem with pybids' `get_metadata` or `get_nearest` methods. We'll need to dig into it.

**Comment by tsalo** [comment]
A quick check using `get_metadata` showed the correct results, so maybe it's a pybids version issue or something else entirely?

**Comment by akimbler** [comment]
@tsalo so it seems like this might have been a pybids version error, this should be resolve with with #10

**Comment by tsalo** [comment]
Closing now.
